routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('invoice.index');
});

Route::resource('invoice', 'InvoiceController', ['except'=>'show','destroy']);
Route::post('delete.invoice','InvoiceController@destroy')->name('invoice.destroy');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Invoice.php
<?php

namespace App\Models;
use App\Traits\EntityTableNameTrait;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    use EntityTableNameTrait;

    protected $guarded = ['id'];

    const ID_PREFIX = 'INV-0000';

    public function translates()
    {
        return $this->hasMany(InvoiceTranslate::class);
    }

    /**
     * @return Carbon
     */
    public function getInvoiceDateInCorrectFormatAttribute()
    {
        return Carbon::parse($this->invoice_date)->format('d-m-Y');
    }

    /**
     * @return Carbon
     */
    public function getSupplyDateInCorrectFormatAttribute()
    {
        return Carbon::parse($this->supply_date)->format('d-m-Y');
    }

    public function getNumberInvoiceAttribute()
    {
        return self::ID_PREFIX.''.$this->id;
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\InvoiceRequest;
use App\Models\Invoice;
use App\Models\Language;
use App\Models\StaticData;
use App\Models\StaticDataTranslate;
use App\Models\User;
use App\Services\InvoiceService;
use App\Traits\LanguageTrait;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class InvoiceController extends Controller
{
    use LanguageTrait, SoftDeletes;
    private $invoiceService;

    public function __construct()
    {
        $this->invoiceService = new InvoiceService();
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create(Request $request)
    {
        if ($request->user()->cant('create', Invoice::class)) {
            return redirect()->route('invoice.index');
        };
        $languages = Language::query()
            ->orderBy('id', 'asc')
            ->get(['id', 'code']);
        $invoiceNumber = Invoice::ID_PREFIX .''. (Invoice::query()->orderBy('id', 'desc')->value('id') + 1 );
        return view('invoice.create', compact('languages', 'invoiceNumber'));
    }

    /**
     * @param InvoiceRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(InvoiceRequest $request)
    {
        if ($request->user()->cant('create', Invoice::class)) {
            return redirect()->route('invoice.index');
        };
        $invoice = Invoice::query()->create([
            'comment' => $request->get('comment'),
            'invoice_date' => $request->get('invoice_date') .' 00:00:00',
            'supply_date' => $request->get('supply_date') .' 00:00:00',
            'user_id' => $request->user()->id,
        ]);

        $this->invoiceService->addTranslates($request, $invoice);
        return redirect()->route('invoice.index');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $langId = $this->getLangId($request);
        $languages = Language::query()->get();
        $staticData = StaticData::query()->with([
            'translates' => function($q) use ($langId){
                $q->where('lang_id',$langId);
            }])->get();
        $invoices = Invoice::query()
            ->with([
                'translates' => function ($q) use ($langId) {
                    $q->where('lang_id', $langId);
                },
            ])
            ->orderBy('created_at', 'desc')
            ->select('id', 'invoice_date', 'supply_date', 'comment')
            ->paginate(10);

        return view('invoice.index', compact('invoices', 'languages','staticData'));
    }

    public function edit(Request $request, $id)
    {
        $invoice = Invoice::query()->whereId($id)->with('translates')->first();
        if ($request->user()->cant('update', $invoice)) {
            return redirect()->route('invoice.index');
        };

        $languages = Language::query()->orderBy('id', 'asc')->get();
        return view('invoice.edit', compact('invoice', 'languages'));
    }

    /**
     * @param InvoiceRequest $request
     * @param Invoice $invoice
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(InvoiceRequest $request, Invoice $invoice)
    {
        if ($request->user()->cant('update', $invoice)) {
            return redirect()->route('invoice.index');
        };
        $invoice->update([
            'invoice_date' =>Carbon::parse($request->get('invoice_date') .'00:00:00')->format('Y-m-d H:i:s'),
            'supply_date' => Carbon::parse($request->get('supply_date') .'00:00:00')->format('Y-m-d H:i:s'),
            'comment' => $request->get('comment'),
        ]);
        $this->invoiceService->addTranslates($request, $invoice);
        return redirect()->route('invoice.index');
    }


    /**
     * @param Request $request
     * @param Invoice $invoice
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Request $request)
    {
        $invoice = Invoice::query()->find($request->get('id'));

        if ($request->user()->cant('delete', $invoice)) {
            return false;
        };

        $deletedItemId = $invoice->id;
        $invoice->delete();
        return response()->json(['deleted_item_id' => $deletedItemId], JsonResponse::HTTP_OK);
    }


}

resources/views/invoice/create.blade.php
@extends('layouts.app')

@section('title')
    add invoice
@endsection

@section('content')
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title" id="horz-layout-card-center">Add invoice</h4>
                </div>
                <div class="card-content collpase show">
                    <div class="card-body">
                        <form class="form form-horizontal" action="{{ route('invoice.store') }}" method="post"
                              enctype="multipart/form-data">
                            @csrf
                            <div class="form-body">
                                <ul class="nav nav-tabs nav-topline">
                                    @foreach($languages as $k => $lang)
                                        @include('admin-panel.form_blocks.tab_nav',['k'=>$k,'code'=>$lang->code])
                                    @endforeach
                                </ul>
                                <div class="tab-content px-1 pt-1 border-grey border-lighten-2 border-0-top">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-sm-5 ml-1 mt-100">
                                                @include('admin-panel.form_blocks.input',['label'=>'Number','name'=>'number','value' => $invoiceNumber,'disabled'=>true])
                                            </div>
                                            <div class="col-sm-5 ml-1 mt-100">
                                                @include('admin-panel.form_blocks.input',['label'=>'Invoice Date:','name'=>'invoice_date','datePicker' => true,'id' => 'invoice_date'])
                                            </div>
                                            <div class="col-sm-6 ml-1 mt-100">
                                                @include('admin-panel.form_blocks.input',['label'=>'Supply Date:','name'=>'supply_date','datePicker' => true, 'id' => 'supply_date'])
                                            </div>
                                        </div>
                                    </div>
                                    @foreach($languages as $k => $lang)
                                        @component('admin-panel.form_blocks.tab_content',['k'=>$k])
                                            @include('admin-panel.form_blocks.textarea',['label'=>'Comment','name'=>'trans_comment[]','index'=>$k])
                                        @endcomponent
                                    @endforeach
                                </div>
                            </div>
                            @include('admin-panel.form_blocks.submit',['title'=>'Save'])
                            @include('admin-panel.form_blocks.error')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/invoice/edit.blade.php
@extends('layouts.app')

@section('title')

@endsection

@section('content')
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title" id="horz-layout-card-center">Edit invoice</h4>
                </div>
                <div class="card-content collpase show">
                    <div class="card-body">
                        <form class="form form-horizontal" action="{{ route('invoice.update',$invoice) }}" method="post"
                              enctype="multipart/form-data">
                            @csrf
                            {{ method_field('PUT') }}
                            <div class="form-body">
                                <ul class="nav nav-tabs nav-topline">
                                    @foreach($languages as $k => $lang)
                                        @include('admin-panel.form_blocks.tab_nav',['k'=>$k,'code'=>$lang->code])
                                    @endforeach
                                </ul>
                                <div class="tab-content px-1 pt-1 border-grey border-lighten-2 border-0-top">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-sm-5 ml-1 mt-100">
                                                @include('admin-panel.form_blocks.input',['label'=>'Number','name'=>'number','value' => $invoice->number_invoice,'disabled'=>true])
                                            </div>
                                            <div class="col-sm-5 ml-1 mt-100">
                                                @include('admin-panel.form_blocks.input',['label'=>'Invoice Date:','name'=>'invoice_date','datePicker' => true,'id' => 'invoice_date', 'value' => $invoice->invoice_date_in_correct_format])
                                            </div>
                                            <div class="col-sm-5 ml-1 mt-100">
                                                @include('admin-panel.form_blocks.input',['label'=>'Supply Date:','name'=>'supply_date','datePicker' => true, 'id' => 'supply_date', 'value' => $invoice->supply_date_in_correct_format])
                                            </div>
                                        </div>
                                    </div>
                                    @foreach($languages as $k => $lang)
                                        @component('admin-panel.form_blocks.tab_content',['k'=>$k])
                                            @include('admin-panel.form_blocks.textarea',['label'=>'Comment','name'=>'trans_comment[]','index'=>$k, 'value' => $invoice->translates->where('lang_id',$lang->id)->first()->comment ?? ''])
                                        @endcomponent
                                    @endforeach
                                </div>
                            </div>
                            @include('admin-panel.form_blocks.submit',['title'=>'Save'])
                            @include('admin-panel.form_blocks.error')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/invoice/index.blade.php
@extends('layouts.app')

@section('title')
    invoices
@endsection

@section('content')

    <section id="configuration">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header d-flex">
                        <div class="title px-4">
                            <h4 class="card-title">Invoice</h4>
                        </div>
                        @auth
                            <div>
                                <a href="{{route('invoice.create')}}" type="button"
                                   class="btn btn-success btn-min-width"><i style="margin-right: 5px"
                                                                            class="fa fa-plus"></i>{{getStaticTranslateBySlug('add-new',$staticData)}}</a>
                            </div>
                        @endauth
                        <div class="dropdown ml-auto mr-3">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{getStaticTranslateBySlug('choose-language',$staticData)}}
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                @foreach($languages as $lang)
                                    <a href="{{route('invoice.index',['lang' => $lang->code])}}" class="d-flex">
                                        <span class="lang px-2 mt-2">
                                            <img width="40px" height="40px" src="{{$lang->icon}}" alt="">
                                            {{$lang->name}}
                                        </span>
                                    </a>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard table-responsive">
                            <table id="invoiceTable" class="table table-striped table-bordered sorted_table">
                                <thead>
                                <tr>
                                    <th>{{getStaticTranslateBySlug('create',$staticData)}}</th>
                                    <th>{{getStaticTranslateBySlug('no',$staticData)}}</th>
                                    <th>{{getStaticTranslateBySlug('supply',$staticData)}}</th>
                                    <th>{{getStaticTranslateBySlug('comment',$staticData)}}</th>
                                    @auth
                                        <th>{{getStaticTranslateBySlug('actions',$staticData)}}</th>
                                    @endauth
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($invoices as $invoice)
                                    <tr id="{{'table-item-id-'.$invoice->id}}">
                                        <td class="pk_id">{{ $invoice->invoice_date_in_correct_format }}</td>
                                        <td>{{ $invoice->number_invoice }}</td>
                                        <td>
                                            {{$invoice->supply_date_in_correct_format}}
                                        </td>
                                        <td>{{ $invoice->translates->first()->comment ?? $invoice->comment }}</td>
                                        @auth
                                            <td>
                                                @include('admin-panel.form_blocks.actions',['route_edit'=>route('invoice.edit',$invoice),'item' => $invoice])
                                            </td>
                                        @endauth
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination">
                                {!! $invoices->render() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>
    @include('admin-panel.form_blocks.delete-modal-window')
@endsection